[project]
name = "rag-chatbot"
version = "0.1.0"
description = "A RAG chatbot project"
requires-python = ">=3.13"
dependencies = [
    "fastapi",
    "uvicorn",
    "python-multipart",
    "langchain-openai",
    "langchain-community",
    "langchain-chroma",
    "chromadb",
    "unstructured[all-docs]",
    "rank-bm25",
    "spacy",
    "python-dotenv",
    "unstructured-inference>=1.6.6",
    "langchain>=1.2.15",
    "langchain-google-genai>=4.2.1",
    "ipykernel>=7.2.0",
    "notebook>=7.5.5",
]
